const {poolPromise,sql}=require('./dbConfig');
class AccountDAL{
 async getProfile(id){const p=await poolPromise;return (await p.request().input('id',sql.Int,Number(id)).query(`SELECT MaNguoiDung,HoTen,Email,SoDienThoai,VaiTro,TinhThanh,QuanHuyen,PhuongXa,DiaChiChiTiet,AnhDaiDien,NgayTao FROM NguoiDung WHERE MaNguoiDung=@id`)).recordset[0]||null;}
 async getProfileByEmail(email){const p=await poolPromise;return (await p.request().input('email',sql.VarChar(255),String(email||'').trim().toLowerCase()).query(`SELECT MaNguoiDung,HoTen,Email,SoDienThoai,VaiTro,TinhThanh,QuanHuyen,PhuongXa,DiaChiChiTiet,AnhDaiDien,NgayTao FROM NguoiDung WHERE LOWER(Email)=@email`)).recordset[0]||null;}
 async getPurchases(id){const p=await poolPromise;return (await p.request().input('id',sql.Int,id).query(`SELECT dh.*,ct.MaSanPham,ct.TenSanPham,ct.DonGia,ct.SoLuong,ct.ThanhTien,nb.HoTen TenNguoiBan FROM DonHang dh JOIN ChiTietDonHang ct ON ct.MaDonHang=dh.MaDonHang LEFT JOIN NguoiDung nb ON nb.MaNguoiDung=ct.MaNguoiBan WHERE dh.MaNguoiMua=@id ORDER BY dh.NgayDat DESC`)).recordset;}
 async updateProfile(id,d){const p=await poolPromise;const q=p.request().input('id',sql.Int,id).input('name',sql.NVarChar(150),String(d.hoTen||'').trim()).input('phone',sql.VarChar(20),String(d.soDienThoai||'').trim()).input('province',sql.NVarChar(100),d.tinhThanh||null).input('district',sql.NVarChar(100),d.quanHuyen||null).input('ward',sql.NVarChar(100),d.phuongXa||null).input('address',sql.NVarChar(255),d.diaChiChiTiet||null); if(!String(d.hoTen||'').trim()) throw Error('Họ tên không được để trống.'); if(!/^0\d{9}$/.test(String(d.soDienThoai||''))) throw Error('Số điện thoại phải gồm 10 số và bắt đầu bằng 0.'); const dup=await p.request().input('phone',sql.VarChar(20),String(d.soDienThoai).trim()).input('id',sql.Int,id).query('SELECT 1 FROM NguoiDung WHERE SoDienThoai=@phone AND MaNguoiDung<>@id'); if(dup.recordset.length) throw Error('Số điện thoại đã được tài khoản khác sử dụng.'); return (await q.query(`UPDATE NguoiDung SET HoTen=@name,SoDienThoai=@phone,TinhThanh=@province,QuanHuyen=@district,PhuongXa=@ward,DiaChiChiTiet=@address,NgayCapNhat=SYSDATETIME() OUTPUT INSERTED.MaNguoiDung,INSERTED.HoTen,INSERTED.Email,INSERTED.SoDienThoai,INSERTED.VaiTro,INSERTED.TinhThanh,INSERTED.QuanHuyen,INSERTED.PhuongXa,INSERTED.DiaChiChiTiet,INSERTED.AnhDaiDien,INSERTED.NgayTao WHERE MaNguoiDung=@id`)).recordset[0];}
 async getSellerStatus(id){const p=await poolPromise;return (await p.request().input('id',sql.Int,id).query(`SELECT TOP 1 TrangThaiDuyet,TenCuaHang,NgayDangKy,NgayDuyet FROM NguoiBan WHERE MaNguoiDung=@id ORDER BY NgayDangKy DESC`)).recordset[0]||null;}
 async getListings(id){const p=await poolPromise;return (await p.request().input('id',sql.Int,id).query(`SELECT sp.*,dm.TenDanhMuc FROM SanPhamDoCu sp JOIN DanhMuc dm ON dm.MaDanhMuc=sp.MaDanhMuc WHERE sp.MaNguoiBan=@id ORDER BY sp.NgayDang DESC`)).recordset;}
 async getSales(id){const p=await poolPromise;return (await p.request().input('id',sql.Int,id).query(`SELECT dh.MaDonHang,dh.TrangThai,dh.NgayDat,dh.TongThanhToan,ct.MaSanPham,ct.TenSanPham,ct.DonGia,ct.SoLuong,ct.ThanhTien,nd.HoTen TenNguoiMua,nd.Email EmailNguoiMua FROM ChiTietDonHang ct JOIN DonHang dh ON dh.MaDonHang=ct.MaDonHang LEFT JOIN NguoiDung nd ON nd.MaNguoiDung=dh.MaNguoiMua WHERE ct.MaNguoiBan=@id ORDER BY dh.NgayDat DESC`)).recordset;}
}
module.exports=new AccountDAL();
