const {poolPromise,sql}=require('./dbConfig');
class NguoiDungDAL{
 async findById(id){const p=await poolPromise;return (await p.request().input('id',sql.Int,Number(id)).query('SELECT TOP 1 * FROM NguoiDung WHERE MaNguoiDung=@id')).recordset[0]||null;}
 async findByEmail(email){const p=await poolPromise;const r=await p.request().input('email',sql.VarChar(255),String(email).trim().toLowerCase()).query('SELECT * FROM NguoiDung WHERE Email=@email');return r.recordset[0];}
 async findByPhone(phone){const p=await poolPromise;const r=await p.request().input('phone',sql.VarChar(20),phone).query('SELECT * FROM NguoiDung WHERE SoDienThoai=@phone');return r.recordset[0];}
 async create(d){const p=await poolPromise;const r=await p.request().input('name',sql.NVarChar(150),d.hoTen).input('email',sql.VarChar(255),d.email.toLowerCase()).input('phone',sql.VarChar(20),d.soDienThoai).input('pass',sql.VarChar(255),d.matKhau).input('tt',sql.NVarChar(100),d.tinhThanh).input('qh',sql.NVarChar(100),d.quanHuyen).input('px',sql.NVarChar(100),d.phuongXa).input('dc',sql.NVarChar(255),d.diaChiChiTiet).query(`INSERT NguoiDung(HoTen,Email,SoDienThoai,MatKhau,TinhThanh,QuanHuyen,PhuongXa,DiaChiChiTiet) OUTPUT INSERTED.MaNguoiDung VALUES(@name,@email,@phone,@pass,@tt,@qh,@px,@dc)`);return r.recordset[0];}
 async createSellerRegistration(d){const p=await poolPromise;await p.request().input('uid',sql.Int,d.maNguoiDung).input('shop',sql.NVarChar(150),d.tenCuaHang).input('phone',sql.VarChar(20),d.soDienThoai).input('tt',sql.NVarChar(100),d.tinhThanh).input('qh',sql.NVarChar(100),d.quanHuyen).input('px',sql.NVarChar(100),d.phuongXa).input('dc',sql.NVarChar(255),d.diaChiChiTiet).input('desc',sql.NVarChar(1000),d.moTa||null).query(`IF EXISTS(SELECT 1 FROM NguoiBan WHERE MaNguoiDung=@uid AND TrangThaiDuyet=N'Chờ duyệt') THROW 50001,N'Hồ sơ đang chờ duyệt.',1; INSERT NguoiBan(MaNguoiDung,TenCuaHang,SoDienThoaiBanHang,TinhThanh,QuanHuyen,PhuongXa,DiaChiChiTiet,MoTa) VALUES(@uid,@shop,@phone,@tt,@qh,@px,@dc,@desc)`);}
 async getSellerRegistrations(){const p=await poolPromise;return (await p.request().query(`SELECT nb.*,nd.HoTen,nd.Email FROM NguoiBan nb JOIN NguoiDung nd ON nd.MaNguoiDung=nb.MaNguoiDung ORDER BY nb.NgayDangKy DESC`)).recordset;}
 async updateSellerRegistration(id,status){const p=await poolPromise;const tx=new sql.Transaction(p);await tx.begin();try{await tx.request().input('id',sql.Int,id).input('st',sql.NVarChar(30),status).query(`UPDATE NguoiBan SET TrangThaiDuyet=@st,NgayDuyet=CASE WHEN @st=N'Đã duyệt' THEN SYSDATETIME() ELSE NULL END WHERE MaNguoiBan=@id`);if(status==='Đã duyệt') await tx.request().input('id',sql.Int,id).query(`UPDATE nd SET VaiTro='seller' FROM NguoiDung nd JOIN NguoiBan nb ON nb.MaNguoiDung=nd.MaNguoiDung WHERE nb.MaNguoiBan=@id`);await tx.commit();}catch(e){await tx.rollback();throw e;}}
}
module.exports=new NguoiDungDAL();
